rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Test -> test_hardware
      
      - rmcs_core::broadcaster::DummyRemote -> dummy_remote
      #- rmcs_core::controller::chassis::SimpleChassisCommander -> simple_chassis_commander

      #- rmcs_core::controller::chassis::ChassisController -> chassis_controller
      
      # 固定功率提供者（替代ChassisPowerController，不限制功率）
      - rmcs_core::controller::chassis::SimplePowerProvider -> power_provider
      
      # 舵轮控制器（电机控制）
      #- rmcs_core::controller::chassis::SteeringWheelController -> steering_wheel_controller
      #- rmcs_core::controller::chassis::VescSteeringWheelController -> vesc_steering_wheel_controller
      - rmcs_core::controller::chassis::VescT4SteeringWheelController -> vesc_t_4_steering_wheel_controller

test_hardware:
  ros__parameters:
    usb_pid_bottom_board: 0x4143
    left_front_zero_point: 4380
    left_back_zero_point: 2363
    right_back_zero_point: 341
    right_front_zero_point: 3795

power_provider:
  ros__parameters:
    power_limit: 99999.0  # 很大的值，实际上不限制功率

steering_wheel_controller:
  ros__parameters:
    mess: 19.0                    # 车体质量 (kg)
    moment_of_inertia: 1.0        # 转动惯量 (kg·m²)
    vehicle_radius: 0.24678       # 车体半径 (m)
    wheel_radius: 0.055           # 轮子半径 (m)
    friction_coefficient: 0.6     # 摩擦系数
    k1: 2.958580e+00              # 电机功率系数1
    k2: 3.082190e-03              # 电机功率系数2
    no_load_power: 11.37          # 空载功率 (W)

vesc_t_4_steering_wheel_controller:
  ros__parameters:
      mess: 19.0                    # 车体质量 (kg)
      moment_of_inertia: 1.0        # 转动惯量 (kg·m²)
      vehicle_radius: 0.24678       # 车体半径 (m)
      wheel_radius: 0.055           # 轮子半径 (m)
      friction_coefficient: 0.6     # 摩擦系数





vesc_steering_wheel_controller:
  ros__parameters:
    wheel_radius: 0.055